import React from 'react';
import email from "../images/email.png";
import "../css/Home.css";
import { Link } from 'react-router-dom';
import contact from "../images/contact.png";

const Email = () => {


    return (
        <div>
            <div className="wrapper indent-top" style={{ marginLeft: '160px', marginRight: '30px' }}>
                <article className="grid_15 suffix_1 prefix_1 alpha">
                    <h2>Email Service</h2>
                    <div className="p" style={{ paddingTop: '10px' }}>
                        <div className="grid_5 alpha" style={{ marginRight: '30px', width: '80px', border: '0' }}>
                            <figure className="img-indent-bot-1" style={{ height: '70px', width: '70px', border: '0', paddingTop: '10px' }}>
                                <img src={email} alt="email" width="87" height="86" style={{ border: 'none' }} />
                            </figure>
                        </div>

                        <div id="left_column">
                            <p>
                                The aim of every brand, invariably, is to reach the maximum number of potential customers. Various methods have been devised by the marketing team in a company, but email marketing potential is being recognised in the present scenario. As more and more people are using computers and emails to communicate, it is a common thing that people check their mails regularly. <br />
                                So, email marketing companies are being hired for the bulk email services, so that people can be reached specifically, with a particular message. Mass email marketing is reaching a stage of maturity where the messages are cryptic and to-the-point where the potential customers are selected with diligence. It is up to the email service provider to get the list of the potential audience and reach them with the messages that are nowadays being generated by the email marketing software.<br />
                            </p>

                            <div>
                                <h2>General uses :</h2>
                            </div>
                            <div className="inner_text floatleft">
                                <ul>
                                    <li>&rsaquo; Marketing</li>
                                    <li>&rsaquo; Price information</li>
                                    <li>&rsaquo; Follow-ups</li>
                                    <li>&rsaquo; Last minute changes</li>
                                    <li>&rsaquo; Offers</li>
                                    <li>&rsaquo; Advertisements</li>
                                    <li>&rsaquo; Tips</li>
                                    <li>&rsaquo; Health Reports</li>
                                </ul>
                            </div>

                            <div className="inner_text floatright">
                                <ul>
                                    <li>&rsaquo; Stock portfolio to clients</li>
                                    <li>&rsaquo; Greetings (Occasional and seasonal)</li>
                                    <li>&rsaquo; Student marks, Fee Remainders and ABSENT Info</li>
                                    <li>&rsaquo; New Product Alerts</li>
                                    <li>&rsaquo; Instant Invoice / Check alerts</li>
                                    <li>&rsaquo; Reminders (Service, Payment etc.)</li>
                                    <li>&rsaquo; To Parents</li>
                                    <li>&rsaquo; and many more</li>
                                </ul>
                            </div>

                            <div>
                                <h2>Support :</h2>
                            </div>
                            <div style={{ textIndent: '15px' }}>
                                <p>
                                    User support is available at no extra cost. BulkSMS offers telephonic and email support. For more information, including available times, please contact Support. If you have any questions regarding any of the BulkSMS products or require further information, please <a href="contacts.html">contact</a> our Sales Department on 8224897414
                                </p>
                                <Link to="/contact">
                                    <img src={contact} style={{ float: 'right' }} alt="Contact" />
                                </Link>
                            </div>
                        </div>

                        <div className="clear"></div>
                    </div>
                    <div className="hr-border-2"></div>
                </article>
            </div>
        </div>
    );
};

export default Email;
